"""Controlled corruption of runs: YAML profiles + apply functions (D-0009)."""

from embodied_sync.corrupt.apply import (
    CorruptionResult,
    apply_burst_stall,
    apply_clock_drift,
    apply_dropped_frames,
    apply_duplicate_samples,
    apply_fixed_latency,
    apply_jitter,
    apply_missing_interval,
    apply_non_monotonic,
    apply_profile,
)
from embodied_sync.corrupt.profile import (
    PROFILE_FORMAT_VERSION,
    BurstStallCorruption,
    ClockDriftCorruption,
    Corruption,
    CorruptionProfile,
    DroppedFramesCorruption,
    DuplicateSamplesCorruption,
    FixedLatencyCorruption,
    JitterCorruption,
    MissingIntervalCorruption,
    NonMonotonicCorruption,
    ProfileError,
    load_profile,
    parse_profile,
)

__all__ = [
    "PROFILE_FORMAT_VERSION",
    "BurstStallCorruption",
    "ClockDriftCorruption",
    "Corruption",
    "CorruptionProfile",
    "DroppedFramesCorruption",
    "DuplicateSamplesCorruption",
    "FixedLatencyCorruption",
    "JitterCorruption",
    "MissingIntervalCorruption",
    "NonMonotonicCorruption",
    "CorruptionResult",
    "ProfileError",
    "apply_burst_stall",
    "apply_clock_drift",
    "apply_dropped_frames",
    "apply_duplicate_samples",
    "apply_fixed_latency",
    "apply_jitter",
    "apply_missing_interval",
    "apply_non_monotonic",
    "apply_profile",
    "load_profile",
    "parse_profile",
]
